### ISSUE TITLE
projects.js

### ISSUE THREAD

**Issue by dzknj** [ksgifford/Portfolio_CF2016#6]
in line 18, you have;
this.completeStatus = this.completeDate ?
 'Completed about '+ this.daysAgo + ' days ago' : 'DRAFT';
 to print how many days ago it was published. it would work just fine as;
this.completeStatus = 'Completed about' + this.daysAgo + 'days ago';
I dont know if you had a reason for adding the
 this.completeDate ? and the :'DRAFT'; 
but if the only reason was to get it to print on the screen than you could take that out. I would like to know if that does anything else, or what you were trying to do by putting it there.

**Comment by ksgifford** [comment]
This code is intended to check whether this.completeDate has a value. If so, it calculates and displays the number of days since completion. If this field is empty, it displays "Draft," indicating that the project has not been completed yet.
